import { createElement } from 'react';
import {
  Baby,
  BookOpen,
  Calendar,
  Check,
  Clock3,
  Flower2,
  HandHeart,
  Lightbulb,
  MessageCircleHeart,
  MoonStar,
  Download,
  Heart,
  Leaf,
  MapPin,
  Medal,
  Sparkles,
  PlayCircle,
  Shield,
  ShoppingBag,
  Star,
  SunMedium,
  Target,
  Users,
  Volume2,
} from 'lucide-react';

const ICONS = {
  heart: Heart,
  star: Star,
  book: BookOpen,
  sparkles: Sparkles,
  play: PlayCircle,
  audio: Volume2,
  clock: Clock3,
  users: Users,
  shield: Shield,
  check: Check,
  calendar: Calendar,
  download: Download,
  map: MapPin,
  bag: ShoppingBag,
  leaf: Leaf,
  flower: Flower2,
  moon: MoonStar,
  sun: SunMedium,
  target: Target,
  medal: Medal,
  bulb: Lightbulb,
  care: HandHeart,
  support: MessageCircleHeart,
  baby: Baby,
};

export const BENEFIT_ICON_OPTIONS = [
  { value: 'heart', label: 'Serce' },
  { value: 'star', label: 'Gwiazda' },
  { value: 'book', label: 'Książka' },
  { value: 'sparkles', label: 'Iskry' },
  { value: 'play', label: 'Odtwarzanie' },
  { value: 'audio', label: 'Audio' },
  { value: 'clock', label: 'Czas' },
  { value: 'users', label: 'Osoby' },
  { value: 'shield', label: 'Tarcza' },
  { value: 'check', label: 'Check' },
  { value: 'calendar', label: 'Kalendarz' },
  { value: 'download', label: 'Pobieranie' },
  { value: 'map', label: 'Mapa' },
  { value: 'bag', label: 'Torba' },
  { value: 'leaf', label: 'Liść' },
  { value: 'flower', label: 'Kwiat' },
  { value: 'moon', label: 'Księżyc' },
  { value: 'sun', label: 'Słońce' },
  { value: 'target', label: 'Cel' },
  { value: 'medal', label: 'Medal' },
  { value: 'bulb', label: 'Pomysł' },
  { value: 'care', label: 'Wsparcie' },
  { value: 'support', label: 'Rozmowa' },
  { value: 'baby', label: 'Dziecko' },
];

export function renderBenefitIcon(iconName, props = {}) {
  const IconComponent = ICONS[iconName] || Check;
  return createElement(IconComponent, props);
}
