export const PAGE_SETTINGS_DEFAULTS = [
  {
    page_key: 'home',
    page_name: 'Strona główna',
    slug: '',
    title: 'Natalia Potocka',
    featured_image_url: '/images/hero_doula.png',
    meta_title: 'Natalia Potocka',
    meta_desc: 'Wsparcie okołoporodowe, konsultacje, szkolenia i produkty cyfrowe Natalii Potockiej.',
    meta_image_url: '/images/hero_doula.png',
    canonical_url: '',
    noindex: 0,
  },
  {
    page_key: 'about',
    page_name: 'O mnie',
    slug: 'o-mnie',
    title: 'O mnie',
    featured_image_url: '/images/about_doula.png',
    meta_title: 'O mnie | Natalia Potocka',
    meta_desc: 'Poznaj podejście i doświadczenie Natalii Potockiej.',
    meta_image_url: '/images/about_doula.png',
    canonical_url: '',
    noindex: 0,
  },
  {
    page_key: 'contact',
    page_name: 'Kontakt',
    slug: 'kontakt',
    title: 'Kontakt',
    featured_image_url: '/images/about_doula.png',
    meta_title: 'Kontakt | Natalia Potocka',
    meta_desc: 'Skontaktuj się z Natalią Potocką w sprawie konsultacji i wsparcia.',
    meta_image_url: '/images/about_doula.png',
    canonical_url: '',
    noindex: 0,
  },
  {
    page_key: 'offer',
    page_name: 'Oferta',
    slug: 'oferta',
    title: 'Oferta',
    featured_image_url: '/images/hero_doula.png',
    meta_title: 'Oferta | Natalia Potocka',
    meta_desc: 'Poznaj ofertę konsultacji, wsparcia i produktów cyfrowych Natalii Potockiej.',
    meta_image_url: '/images/hero_doula.png',
    canonical_url: '',
    noindex: 0,
  },
  {
    page_key: 'privacy',
    page_name: 'Polityka prywatności',
    slug: 'polityka-prywatnosci',
    title: 'Polityka prywatności',
    featured_image_url: '/images/hero_doula.png',
    meta_title: 'Polityka prywatności | Natalia Potocka',
    meta_desc: 'Informacje o przetwarzaniu danych osobowych i technicznych zasadach działania strony internetowej.',
    meta_image_url: '/images/hero_doula.png',
    canonical_url: '',
    noindex: 0,
  },
  {
    page_key: 'terms',
    page_name: 'Regulamin sklepu',
    slug: 'regulamin-sklepu',
    title: 'Regulamin sklepu',
    featured_image_url: '/images/hero_doula.png',
    meta_title: 'Regulamin sklepu | Natalia Potocka',
    meta_desc: 'Zasady zakupu i korzystania z produktów cyfrowych dostępnych na stronie Natalii Potockiej.',
    meta_image_url: '/images/hero_doula.png',
    canonical_url: '',
    noindex: 0,
  },
];

export const PAGE_SETTINGS_BY_KEY = Object.fromEntries(
  PAGE_SETTINGS_DEFAULTS.map((page) => [page.page_key, page]),
);

export const PAGE_RESERVED_SLUGS = new Set([
  'api',
  'administrator',
  'panel',
  'logowanie',
  'zapomnialam-hasla',
  'resetowanie-hasla',
]);