name: Wdróż Frontend na GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci || npm install

      - name: Build project
        working-directory: ./frontend
        # Ustawiamy base na nazwę Twojego repozytorium (/natalia-potocka/)
        run: npx vite build --base=/natalia-potocka/

      - name: Fix Routing for GitHub Pages (React Router)
        working-directory: ./public
        # Kopiujemy plik, aby GH Pages nie wyrzucało 404 przy wejściu np. na /o-mnie bezpośrednio z paska
        run: cp index.html 404.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./public"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
